using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using System.Text.RegularExpressions;
using FinanceManager.Core.Entities;
using FinanceManager.Core.Enums;
using FinanceManager.Core.Exceptions;
using FinanceManager.Core.Interfaces.Repositories;
using FinanceManager.API.DTOs.Requests;
using FinanceManager.API.DTOs.Responses;

namespace FinanceManager.API.Controllers;

[Authorize]
[ApiController]
[Route("api/[controller]")]
public class CategoryRulesController : ControllerBase
{
    private readonly IUnitOfWork _unitOfWork;

    public CategoryRulesController(IUnitOfWork unitOfWork)
    {
        _unitOfWork = unitOfWork;
    }

    private Guid GetUserId()
    {
        var userIdClaim = User.FindFirst(ClaimTypes.NameIdentifier);
        if (userIdClaim == null)
            throw new UnauthorizedException("User not authenticated");
        return Guid.Parse(userIdClaim.Value);
    }

    /// <summary>
    /// Gets all category rules for the authenticated user
    /// </summary>
    [HttpGet]
    public async Task<ActionResult<IEnumerable<CategoryRuleResponse>>> GetRules(
        [FromQuery] bool includeInactive = false,
        [FromQuery] Guid? categoryId = null)
    {
        var userId = GetUserId();
        var rules = await _unitOfWork.CategoryRules.GetActiveRulesByUserIdAsync(userId);

        // Apply filters
        var filteredRules = rules.AsEnumerable();

        if (!includeInactive)
        {
            filteredRules = filteredRules.Where(r => r.IsActive);
        }

        if (categoryId.HasValue)
        {
            filteredRules = filteredRules.Where(r => r.CategoryId == categoryId.Value);
        }

        var response = filteredRules.Select(r => new CategoryRuleResponse
        {
            Id = r.Id,
            RuleName = r.RuleName,
            CategoryId = r.CategoryId,
            CategoryName = r.Category?.Name ?? "Unknown",
            MatchType = r.MatchType,
            Pattern = r.Pattern,
            IsCaseSensitive = r.IsCaseSensitive,
            Priority = r.Priority,
            IsActive = r.IsActive,
            IsAutoGenerated = r.IsAutoGenerated,
            MatchCount = r.MatchCount,
            LastMatchedDate = r.LastMatchedDate,
            CreatedDate = r.CreatedDate
        }).OrderByDescending(r => r.Priority).ToList();

        return Ok(response);
    }

    /// <summary>
    /// Gets a specific category rule by ID
    /// </summary>
    [HttpGet("{id}")]
    public async Task<ActionResult<CategoryRuleResponse>> GetRule(int id)
    {
        var userId = GetUserId();
        var rule = await _unitOfWork.CategoryRules.GetByIdAndUserIdAsync(id, userId);

        if (rule == null)
        {
            throw new NotFoundException("Category rule not found");
        }

        var response = new CategoryRuleResponse
        {
            Id = rule.Id,
            RuleName = rule.RuleName,
            CategoryId = rule.CategoryId,
            CategoryName = rule.Category?.Name ?? "Unknown",
            MatchType = rule.MatchType,
            Pattern = rule.Pattern,
            IsCaseSensitive = rule.IsCaseSensitive,
            Priority = rule.Priority,
            IsActive = rule.IsActive,
            IsAutoGenerated = rule.IsAutoGenerated,
            MatchCount = rule.MatchCount,
            LastMatchedDate = rule.LastMatchedDate,
            CreatedDate = rule.CreatedDate
        };

        return Ok(response);
    }

    /// <summary>
    /// Creates a new category rule
    /// </summary>
    [HttpPost]
    public async Task<ActionResult<CategoryRuleResponse>> CreateRule([FromBody] CategoryRuleRequest request)
    {
        var userId = GetUserId();

        // Validate category exists and belongs to user
        var category = await _unitOfWork.Categories.GetByIdAsync(request.CategoryId);
        if (category == null || (category.UserId != null && category.UserId != userId))
        {
            throw new NotFoundException("Category not found");
        }

        // Validate Priority range (1-100)
        if (request.Priority < 1 || request.Priority > 100)
        {
            throw new ValidationException("Priority must be between 1 and 100");
        }

        // Validate regex pattern if MatchType is Regex
        if (request.MatchType == RuleMatchType.Regex)
        {
            try
            {
                Regex.IsMatch("test", request.Pattern);
            }
            catch (ArgumentException)
            {
                throw new ValidationException("Invalid regex pattern");
            }
        }

        var rule = new CategoryRule
        {
            UserId = userId,
            CategoryId = request.CategoryId,
            RuleName = request.RuleName,
            MatchType = request.MatchType,
            Pattern = request.Pattern,
            IsCaseSensitive = request.IsCaseSensitive,
            Priority = request.Priority,
            IsActive = true,
            IsAutoGenerated = false,
            MatchCount = 0,
            CreatedDate = DateTime.UtcNow
        };

        await _unitOfWork.CategoryRules.AddAsync(rule);
        await _unitOfWork.SaveChangesAsync();

        var response = new CategoryRuleResponse
        {
            Id = rule.Id,
            RuleName = rule.RuleName,
            CategoryId = rule.CategoryId,
            CategoryName = category.Name,
            MatchType = rule.MatchType,
            Pattern = rule.Pattern,
            IsCaseSensitive = rule.IsCaseSensitive,
            Priority = rule.Priority,
            IsActive = rule.IsActive,
            IsAutoGenerated = rule.IsAutoGenerated,
            MatchCount = rule.MatchCount,
            LastMatchedDate = rule.LastMatchedDate,
            CreatedDate = rule.CreatedDate
        };

        return CreatedAtAction(nameof(GetRule), new { id = rule.Id }, response);
    }

    /// <summary>
    /// Updates an existing category rule
    /// </summary>
    [HttpPut("{id}")]
    public async Task<ActionResult<CategoryRuleResponse>> UpdateRule(int id, [FromBody] CategoryRuleRequest request)
    {
        var userId = GetUserId();
        var rule = await _unitOfWork.CategoryRules.GetByIdAndUserIdAsync(id, userId);

        if (rule == null)
        {
            throw new NotFoundException("Category rule not found");
        }

        // Validate category exists and belongs to user
        var category = await _unitOfWork.Categories.GetByIdAsync(request.CategoryId);
        if (category == null || (category.UserId != null && category.UserId != userId))
        {
            throw new NotFoundException("Category not found");
        }

        // Validate Priority range (1-100)
        if (request.Priority < 1 || request.Priority > 100)
        {
            throw new ValidationException("Priority must be between 1 and 100");
        }

        // Validate regex pattern if MatchType is Regex
        if (request.MatchType == RuleMatchType.Regex)
        {
            try
            {
                Regex.IsMatch("test", request.Pattern);
            }
            catch (ArgumentException)
            {
                throw new ValidationException("Invalid regex pattern");
            }
        }

        // Update rule properties
        rule.RuleName = request.RuleName;
        rule.CategoryId = request.CategoryId;
        rule.MatchType = request.MatchType;
        rule.Pattern = request.Pattern;
        rule.IsCaseSensitive = request.IsCaseSensitive;
        rule.Priority = request.Priority;

        await _unitOfWork.CategoryRules.UpdateAsync(rule);
        await _unitOfWork.SaveChangesAsync();

        var response = new CategoryRuleResponse
        {
            Id = rule.Id,
            RuleName = rule.RuleName,
            CategoryId = rule.CategoryId,
            CategoryName = category.Name,
            MatchType = rule.MatchType,
            Pattern = rule.Pattern,
            IsCaseSensitive = rule.IsCaseSensitive,
            Priority = rule.Priority,
            IsActive = rule.IsActive,
            IsAutoGenerated = rule.IsAutoGenerated,
            MatchCount = rule.MatchCount,
            LastMatchedDate = rule.LastMatchedDate,
            CreatedDate = rule.CreatedDate
        };

        return Ok(response);
    }

    /// <summary>
    /// Deletes (deactivates) a category rule
    /// </summary>
    [HttpDelete("{id}")]
    public async Task<ActionResult> DeleteRule(int id)
    {
        var userId = GetUserId();
        var rule = await _unitOfWork.CategoryRules.GetByIdAndUserIdAsync(id, userId);

        if (rule == null)
        {
            throw new NotFoundException("Category rule not found");
        }

        // Soft delete: deactivate instead of removing
        rule.IsActive = false;
        await _unitOfWork.CategoryRules.UpdateAsync(rule);
        await _unitOfWork.SaveChangesAsync();

        return NoContent();
    }
}
