using FinanceManager.Core.Entities;
using FinanceManager.Core.Enums;
using FinanceManager.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;

namespace FinanceManager.Infrastructure.Seeders;

/// <summary>
/// Seeds predefined category rules for automatic transaction categorization
/// </summary>
public static class CategoryRuleSeeder
{
    public static async Task SeedCategoryRulesAsync(ApplicationDbContext context, Guid systemUserId)
    {
        // Check if rules already exist for system user
        var existingRules = await context.CategoryRules
            .Where(r => r.UserId == systemUserId)
            .AnyAsync();

        if (existingRules)
        {
            Console.WriteLine("Category rules already seeded. Skipping...");
            return;
        }

        // Get system categories by name
        var categories = await context.Categories
            .Where(c => c.IsSystem && c.IsActive)
            .ToDictionaryAsync(c => c.Name.ToLower());

        if (!categories.Any())
        {
            Console.WriteLine("No system categories found. Skipping category rules seeding...");
            return;
        }

        var rules = new List<CategoryRule>();

        // ALIMENTACIÓN (Groceries)
        if (categories.ContainsKey("alimentación"))
        {
            rules.Add(new CategoryRule
            {
                UserId = systemUserId,
                CategoryId = categories["alimentación"].Id,
                RuleName = "Supermercados Dominicanos",
                MatchType = RuleMatchType.Contains,
                Pattern = "SUPERM|NACIONAL|SIRENA|BRAVO|JUMBO|POLA|MERCADO",
                IsCaseSensitive = false,
                Priority = 85,
                IsAutoGenerated = false,
                IsActive = true,
                CreatedDate = DateTime.UtcNow
            });
        }

        // TRANSPORTE (Transportation)
        if (categories.ContainsKey("transporte"))
        {
            rules.AddRange(new[]
            {
                new CategoryRule
                {
                    UserId = systemUserId,
                    CategoryId = categories["transporte"].Id,
                    RuleName = "Estaciones de Gasolina",
                    MatchType = RuleMatchType.Contains,
                    Pattern = "ESSO|SHELL|TOTAL|TEXACO|GAS|COMBUSTIBLE",
                    IsCaseSensitive = false,
                    Priority = 90,
                    IsAutoGenerated = false,
                    IsActive = true,
                    CreatedDate = DateTime.UtcNow
                },
                new CategoryRule
                {
                    UserId = systemUserId,
                    CategoryId = categories["transporte"].Id,
                    RuleName = "Uber y Taxis",
                    MatchType = RuleMatchType.Contains,
                    Pattern = "UBER|TAXI|CABIFY|DIDI|TRANSPORTE",
                    IsCaseSensitive = false,
                    Priority = 88,
                    IsAutoGenerated = false,
                    IsActive = true,
                    CreatedDate = DateTime.UtcNow
                }
            });
        }

        // SALUD (Health)
        if (categories.ContainsKey("salud"))
        {
            rules.Add(new CategoryRule
            {
                UserId = systemUserId,
                CategoryId = categories["salud"].Id,
                RuleName = "Farmacias",
                MatchType = RuleMatchType.Contains,
                Pattern = "FARMA|CAROL|VALUE|FARMACITY",
                IsCaseSensitive = false,
                Priority = 87,
                IsAutoGenerated = false,
                IsActive = true,
                CreatedDate = DateTime.UtcNow
            });
        }

        // ENTRETENIMIENTO (Entertainment)
        if (categories.ContainsKey("entretenimiento"))
        {
            rules.AddRange(new[]
            {
                new CategoryRule
                {
                    UserId = systemUserId,
                    CategoryId = categories["entretenimiento"].Id,
                    RuleName = "Streaming Services",
                    MatchType = RuleMatchType.Contains,
                    Pattern = "NETFLIX|SPOTIFY|AMAZON|DISNEY|HBO|PRIME|APPLE MUSIC",
                    IsCaseSensitive = false,
                    Priority = 85,
                    IsAutoGenerated = false,
                    IsActive = true,
                    CreatedDate = DateTime.UtcNow
                },
                new CategoryRule
                {
                    UserId = systemUserId,
                    CategoryId = categories["entretenimiento"].Id,
                    RuleName = "Restaurantes y Cafés",
                    MatchType = RuleMatchType.Contains,
                    Pattern = "RESTAURANT|PIZZ|BURGER|CAFE|CAFETER|REST\\.|CAMINETTO|OPERA",
                    IsCaseSensitive = false,
                    Priority = 70,
                    IsAutoGenerated = false,
                    IsActive = true,
                    CreatedDate = DateTime.UtcNow
                }
            });
        }

        // SERVICIOS (Utilities)
        if (categories.ContainsKey("servicios"))
        {
            rules.AddRange(new[]
            {
                new CategoryRule
                {
                    UserId = systemUserId,
                    CategoryId = categories["servicios"].Id,
                    RuleName = "Electricidad RD",
                    MatchType = RuleMatchType.Contains,
                    Pattern = "EDEESTE|EDENORTE|EDESUR|CDEEE|ELECT",
                    IsCaseSensitive = false,
                    Priority = 92,
                    IsAutoGenerated = false,
                    IsActive = true,
                    CreatedDate = DateTime.UtcNow
                },
                new CategoryRule
                {
                    UserId = systemUserId,
                    CategoryId = categories["servicios"].Id,
                    RuleName = "Telefonía e Internet RD",
                    MatchType = RuleMatchType.Contains,
                    Pattern = "CLARO|ALTICE|VIVA|TRICOM|TELEFON",
                    IsCaseSensitive = false,
                    Priority = 92,
                    IsAutoGenerated = false,
                    IsActive = true,
                    CreatedDate = DateTime.UtcNow
                }
            });
        }

        // VIVIENDA (Home)
        if (categories.ContainsKey("vivienda"))
        {
            rules.AddRange(new[]
            {
                new CategoryRule
                {
                    UserId = systemUserId,
                    CategoryId = categories["vivienda"].Id,
                    RuleName = "Alquiler y Renta",
                    MatchType = RuleMatchType.Contains,
                    Pattern = "ALQUILER|RENTA|RENT|ARRIENDO",
                    IsCaseSensitive = false,
                    Priority = 95,
                    IsAutoGenerated = false,
                    IsActive = true,
                    CreatedDate = DateTime.UtcNow
                },
                new CategoryRule
                {
                    UserId = systemUserId,
                    CategoryId = categories["vivienda"].Id,
                    RuleName = "Ferreterías y Construcción",
                    MatchType = RuleMatchType.Contains,
                    Pattern = "FERRET|CONSTRUC|HOME DEPOT|EPA",
                    IsCaseSensitive = false,
                    Priority = 73,
                    IsAutoGenerated = false,
                    IsActive = true,
                    CreatedDate = DateTime.UtcNow
                }
            });
        }

        // OTROS INGRESOS (Other Income) - for cashback
        if (categories.ContainsKey("otros ingresos"))
        {
            rules.Add(new CategoryRule
            {
                UserId = systemUserId,
                CategoryId = categories["otros ingresos"].Id,
                RuleName = "Cashback y Recompensas",
                MatchType = RuleMatchType.Contains,
                Pattern = "CASHBACK|CASH BACK|RECOMPENSA|REWARD|PROMOCION",
                IsCaseSensitive = false,
                Priority = 98,
                IsAutoGenerated = false,
                IsActive = true,
                CreatedDate = DateTime.UtcNow
            });
        }

        // OTROS GASTOS (Other Expenses) - for bank fees
        if (categories.ContainsKey("otros gastos"))
        {
            rules.AddRange(new[]
            {
                new CategoryRule
                {
                    UserId = systemUserId,
                    CategoryId = categories["otros gastos"].Id,
                    RuleName = "Comisiones Bancarias",
                    MatchType = RuleMatchType.Contains,
                    Pattern = "COMISION|FEE|CARGO|PENALIDAD|SOBREGIRO",
                    IsCaseSensitive = false,
                    Priority = 95,
                    IsAutoGenerated = false,
                    IsActive = true,
                    CreatedDate = DateTime.UtcNow
                },
                new CategoryRule
                {
                    UserId = systemUserId,
                    CategoryId = categories["otros gastos"].Id,
                    RuleName = "Seguros y Protección",
                    MatchType = RuleMatchType.Contains,
                    Pattern = "SEGURO|PROTECCION FINANCIERA|INSURANCE",
                    IsCaseSensitive = false,
                    Priority = 88,
                    IsAutoGenerated = false,
                    IsActive = true,
                    CreatedDate = DateTime.UtcNow
                }
            });
        }

        // ========== REGLAS PARA ESPAÑA ==========

        // ALIMENTACIÓN - Supermercados Españoles
        if (categories.ContainsKey("alimentación"))
        {
            rules.AddRange(new[]
            {
                new CategoryRule
                {
                    UserId = systemUserId,
                    CategoryId = categories["alimentación"].Id,
                    RuleName = "Supermercados España - Líderes",
                    MatchType = RuleMatchType.Contains,
                    Pattern = "MERCADONA|CARREFOUR|LIDL|DIA|EROSKI",
                    IsCaseSensitive = false,
                    Priority = 85,
                    IsAutoGenerated = false,
                    IsActive = true,
                    CreatedDate = DateTime.UtcNow
                },
                new CategoryRule
                {
                    UserId = systemUserId,
                    CategoryId = categories["alimentación"].Id,
                    RuleName = "Supermercados España - Otros",
                    MatchType = RuleMatchType.Contains,
                    Pattern = "ALCAMPO|ALDI|CONSUM|EL CORTE INGLES ALIMENT|HIPERCOR|SIMPLY",
                    IsCaseSensitive = false,
                    Priority = 83,
                    IsAutoGenerated = false,
                    IsActive = true,
                    CreatedDate = DateTime.UtcNow
                }
            });
        }

        // TRANSPORTE - Gasolineras España
        if (categories.ContainsKey("transporte"))
        {
            rules.AddRange(new[]
            {
                new CategoryRule
                {
                    UserId = systemUserId,
                    CategoryId = categories["transporte"].Id,
                    RuleName = "Gasolineras España - Principales",
                    MatchType = RuleMatchType.Contains,
                    Pattern = "REPSOL|CEPSA|BP|GALP|SHELL",
                    IsCaseSensitive = false,
                    Priority = 90,
                    IsAutoGenerated = false,
                    IsActive = true,
                    CreatedDate = DateTime.UtcNow
                },
                new CategoryRule
                {
                    UserId = systemUserId,
                    CategoryId = categories["transporte"].Id,
                    RuleName = "Gasolineras España - Low Cost",
                    MatchType = RuleMatchType.Contains,
                    Pattern = "PLENOIL|BALLENOIL|PETROPRIX",
                    IsCaseSensitive = false,
                    Priority = 89,
                    IsAutoGenerated = false,
                    IsActive = true,
                    CreatedDate = DateTime.UtcNow
                },
                new CategoryRule
                {
                    UserId = systemUserId,
                    CategoryId = categories["transporte"].Id,
                    RuleName = "Transporte Público España",
                    MatchType = RuleMatchType.Contains,
                    Pattern = "RENFE|METRO|EMT|TMB|CERCANIAS|AVANT",
                    IsCaseSensitive = false,
                    Priority = 88,
                    IsAutoGenerated = false,
                    IsActive = true,
                    CreatedDate = DateTime.UtcNow
                }
            });
        }

        // SERVICIOS - Telecomunicaciones España
        if (categories.ContainsKey("servicios"))
        {
            rules.AddRange(new[]
            {
                new CategoryRule
                {
                    UserId = systemUserId,
                    CategoryId = categories["servicios"].Id,
                    RuleName = "Telefonía España",
                    MatchType = RuleMatchType.Contains,
                    Pattern = "MOVISTAR|VODAFONE|ORANGE|JAZZTEL|YOIGO|MASMOVIL|PEPEPHONE",
                    IsCaseSensitive = false,
                    Priority = 92,
                    IsAutoGenerated = false,
                    IsActive = true,
                    CreatedDate = DateTime.UtcNow
                },
                new CategoryRule
                {
                    UserId = systemUserId,
                    CategoryId = categories["servicios"].Id,
                    RuleName = "Electricidad España",
                    MatchType = RuleMatchType.Contains,
                    Pattern = "ENDESA|IBERDROLA|NATURGY|GAS NATURAL|EDP",
                    IsCaseSensitive = false,
                    Priority = 92,
                    IsAutoGenerated = false,
                    IsActive = true,
                    CreatedDate = DateTime.UtcNow
                }
            });
        }

        // COMPRAS - Tiendas España
        if (categories.ContainsKey("compras"))
        {
            rules.AddRange(new[]
            {
                new CategoryRule
                {
                    UserId = systemUserId,
                    CategoryId = categories["compras"].Id,
                    RuleName = "Grandes Almacenes España",
                    MatchType = RuleMatchType.Contains,
                    Pattern = "EL CORTE INGLES|FNAC|MEDIAMARKT|WORTEN|DECATHLON",
                    IsCaseSensitive = false,
                    Priority = 80,
                    IsAutoGenerated = false,
                    IsActive = true,
                    CreatedDate = DateTime.UtcNow
                },
                new CategoryRule
                {
                    UserId = systemUserId,
                    CategoryId = categories["compras"].Id,
                    RuleName = "Moda España",
                    MatchType = RuleMatchType.Contains,
                    Pattern = "ZARA|H&M|MANGO|PULL&BEAR|BERSHKA|MASSIMO DUTTI|PRIMARK",
                    IsCaseSensitive = false,
                    Priority = 78,
                    IsAutoGenerated = false,
                    IsActive = true,
                    CreatedDate = DateTime.UtcNow
                }
            });
        }

        // ENTRETENIMIENTO - Restaurantes España
        if (categories.ContainsKey("entretenimiento"))
        {
            rules.AddRange(new[]
            {
                new CategoryRule
                {
                    UserId = systemUserId,
                    CategoryId = categories["entretenimiento"].Id,
                    RuleName = "Fast Food España",
                    MatchType = RuleMatchType.Contains,
                    Pattern = "MCDONALDS|BURGER KING|KFC|TELEPIZZA|DOMINO|SUBWAY|100 MONTADITOS",
                    IsCaseSensitive = false,
                    Priority = 75,
                    IsAutoGenerated = false,
                    IsActive = true,
                    CreatedDate = DateTime.UtcNow
                },
                new CategoryRule
                {
                    UserId = systemUserId,
                    CategoryId = categories["entretenimiento"].Id,
                    RuleName = "Cafeterías España",
                    MatchType = RuleMatchType.Contains,
                    Pattern = "STARBUCKS|VIPS|RODILLA|GRANIER|DUNKIN",
                    IsCaseSensitive = false,
                    Priority = 73,
                    IsAutoGenerated = false,
                    IsActive = true,
                    CreatedDate = DateTime.UtcNow
                }
            });
        }

        // SALUD - Farmacias España
        if (categories.ContainsKey("salud"))
        {
            rules.Add(new CategoryRule
            {
                UserId = systemUserId,
                CategoryId = categories["salud"].Id,
                RuleName = "Farmacias España",
                MatchType = RuleMatchType.Contains,
                Pattern = "FARMACIA|FARMA|PARAFARMACIA",
                IsCaseSensitive = false,
                Priority = 87,
                IsAutoGenerated = false,
                IsActive = true,
                CreatedDate = DateTime.UtcNow
            });
        }

        // Insert all rules
        if (rules.Any())
        {
            await context.CategoryRules.AddRangeAsync(rules);
            await context.SaveChangesAsync();
            Console.WriteLine($"✅ Seeded {rules.Count} predefined category rules");
        }
    }
}
