using FinanceManager.Core.Enums;

namespace FinanceManager.Core.Entities;

/// <summary>
/// Represents an auto-categorization rule that matches transaction descriptions to categories
/// </summary>
public class CategoryRule
{
    public int Id { get; set; }
    public Guid UserId { get; set; }
    public Guid CategoryId { get; set; }

    /// <summary>
    /// User-friendly name for the rule
    /// </summary>
    public string RuleName { get; set; } = string.Empty;

    /// <summary>
    /// Type of pattern matching to apply
    /// </summary>
    public RuleMatchType MatchType { get; set; }

    /// <summary>
    /// Pattern to match against transaction descriptions
    /// </summary>
    public string Pattern { get; set; } = string.Empty;

    /// <summary>
    /// Whether pattern matching should be case sensitive
    /// </summary>
    public bool IsCaseSensitive { get; set; } = false;

    /// <summary>
    /// Priority for rule evaluation (1-100, higher priority evaluated first)
    /// </summary>
    public int Priority { get; set; } = 50;

    /// <summary>
    /// Number of times this rule has successfully matched transactions
    /// </summary>
    public int MatchCount { get; set; } = 0;

    /// <summary>
    /// Last date when this rule matched a transaction
    /// </summary>
    public DateTime? LastMatchedDate { get; set; }

    /// <summary>
    /// Indicates if rule was auto-generated by ML or created by user
    /// </summary>
    public bool IsAutoGenerated { get; set; } = false;

    /// <summary>
    /// Soft delete flag
    /// </summary>
    public bool IsActive { get; set; } = true;

    public DateTime CreatedDate { get; set; }

    // Navigation properties
    public User User { get; set; } = null!;
    public Category Category { get; set; } = null!;
}
