using FinanceManager.Core.Enums;

namespace FinanceManager.API.DTOs.Responses;

public class CategoryRuleResponse
{
    public int Id { get; set; }
    public string RuleName { get; set; } = string.Empty;
    public Guid CategoryId { get; set; }
    public string CategoryName { get; set; } = string.Empty;
    public RuleMatchType MatchType { get; set; }
    public string Pattern { get; set; } = string.Empty;
    public bool IsCaseSensitive { get; set; }
    public int Priority { get; set; }
    public int MatchCount { get; set; }
    public DateTime? LastMatchedDate { get; set; }
    public bool IsAutoGenerated { get; set; }
    public bool IsActive { get; set; }
    public DateTime CreatedDate { get; set; }
}
